[package]
name = "common-runtime"
version = "0.1.0"
description = "Neumann, OAK's Canary Network"
authors = ["OAK Developement Team"]
license = "GPL-3.0"
homepage = "https://oak.tech"
repository = 'https://github.com/OAK-Foundation/OAK-blockchain'
edition = "2021"

[dependencies]
