version: 0.2

env:
  secrets-manager:
    DOCKERHUB_PASS: "dockerhub/credentials:password"
    DOCKERHUB_USERNAME: "dockerhub/credentials:username"

phases:
  pre_build:
    commands:
      - echo Logging in to Docker hub...
      - docker login --username $DOCKERHUB_USERNAME --password $DOCKERHUB_PASS
  build:
    commands:
      - echo Build started on `date`
      - cargo install --git https://github.com/chevdor/srtool-cli
      - srtool help
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - neumann_runtime.compact.compressed.wasm
    - neumann_runtime.compact.wasm
    - neumann-dev/*
    - neumann-local/*
    - neumann-staging/*
    - neumann-latest/*
  name: neumann-$IMAGE_TAG
