version: 0.2

env:
  secrets-manager:
    DOCKERHUB_PASS: "dockerhub/credentials:password"
    DOCKERHUB_USERNAME: "dockerhub/credentials:username"

phases:
  pre_build:
    commands:
      - echo Logging in to Docker hub...
      - docker login --username $DOCKERHUB_USERNAME --password $DOCKERHUB_PASS
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -f ./docker/neumann/Dockerfile -t oaknetwork/neumann:$IMAGE_TAG .
      - docker run oaknetwork/neumann:$IMAGE_TAG export-genesis-state --chain=$CHAIN > genesis-state
      - docker run oaknetwork/neumann:$IMAGE_TAG export-genesis-wasm --chain=$CHAIN > genesis-wasm
      - docker run oaknetwork/neumann:$IMAGE_TAG build-spec --disable-default-bootnode --chain=$CHAIN --raw > $CHAIN.json
      - docker run --entrypoint cat oaknetwork/neumann:$IMAGE_TAG /tmp/neumann_runtime.compact.compressed.wasm > neumann_runtime.compact.compressed.wasm
      - docker run --entrypoint cat oaknetwork/neumann:$IMAGE_TAG /tmp/neumann_runtime.compact.wasm > neumann_runtime.compact.wasm
      - echo Pushing the Docker image...
      - docker push oaknetwork/neumann:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
