version: 0.2

env:
  secrets-manager:
    DOCKERHUB_PASS: "dockerhub/credentials:password"
    DOCKERHUB_USERNAME: "dockerhub/credentials:username"

phases:
  pre_build:
    commands:
      - echo Build started on `date`
  build:
    commands:
      - echo Logging in to Docker hub...
      - docker login --username $DOCKERHUB_USERNAME --password $DOCKERHUB_PASS
      - echo Building the Docker image...
      - docker build -f ./docker/turing/Dockerfile -t oaknetwork/turing:$IMAGE_TAG .
      - echo Building artifacts...
      - mkdir turing-dev turing-staging turing-live
      - docker run oaknetwork/turing:$IMAGE_TAG export-genesis-state --chain=turing-dev > turing-dev/genesis-state
      - docker run oaknetwork/turing:$IMAGE_TAG export-genesis-state --chain=turing-staging > turing-staging/genesis-state
      - docker run oaknetwork/turing:$IMAGE_TAG export-genesis-state --chain=turing-live > turing-live/genesis-state
      - docker run oaknetwork/turing:$IMAGE_TAG export-genesis-wasm --chain=turing-dev > turing-dev/genesis-wasm
      - docker run oaknetwork/turing:$IMAGE_TAG export-genesis-wasm --chain=turing-staging > turing-staging/genesis-wasm
      - docker run oaknetwork/turing:$IMAGE_TAG export-genesis-wasm --chain=turing-live > turing-live/genesis-wasm
      - echo Pushing the Docker image...
      - docker push oaknetwork/turing:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - turing-dev/*
    - turing-staging/*
    - turing-live/*
  name: turing-genesis-$IMAGE_TAG
