version: 0.2

env:
  secrets-manager:
    DOCKERHUB_PASS: "dockerhub/credentials:password"
    DOCKERHUB_USERNAME: "dockerhub/credentials:username"

phases:
  pre_build:
    commands:
      - echo Build started on `date`
  build:
    commands:
      - echo Logging in to Docker hub...
      - docker login --username $DOCKERHUB_USERNAME --password $DOCKERHUB_PASS
      - echo Building the Docker image...
      - docker pull oaknetwork/turing:latest
      - echo Building artifacts...
      - mkdir -p turing-latest/chain_specs turing-staging-latest/chain_specs
      - id=$(docker create oaknetwork/turing:latest)
      - docker cp $id:/oak/oak-collator turing-latest/
      - docker cp $id:/oak/resources/turing-live-chain-spec.json turing-latest/chain_specs/chain_spec.json
      - docker cp $id:/oak/oak-collator turing-staging-latest/
      - docker cp $id:/oak/resources/turing-staging-chain-spec.json turing-staging-latest/chain_specs/chain_spec.json
      - docker rm -v $id
      - curl -o turing-latest/chain_specs/relay_chain_spec.json https://raw.githubusercontent.com/paritytech/polkadot/master/node/service/chain-specs/kusama.json
      - curl -o turing-staging-latest/chain_specs/relay_chain_spec.json https://raw.githubusercontent.com/paritytech/polkadot/master/node/service/chain-specs/rococo.json
      - cd turing-latest/ && zip -r turing-$IMAGE_TAG.zip . && mv turing-$IMAGE_TAG.zip .. && cd ..
      - cd turing-staging-latest/ && zip -r turing-staging-$IMAGE_TAG.zip . && mv turing-staging-$IMAGE_TAG.zip .. && cd ..
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - '*.zip'
  secondary-artifacts:
    artifact1:
      base-directory: $CODEBUILD_SRC_DIR
      files:
        - 'turing-latest/**'
      name: tuing-$IMAGE_TAGE
