[settings]
provider = "native"
timeout = 1000

[relaychain]
default_command = "../polkadot/target/release/polkadot"
chain = "rococo-local"

[[relaychain.nodes]]
name = "alice"

[[relaychain.nodes]]
name = "bob"

[[parachains]]
id = 2114
cumulus_based = true
chain = "turing-dev"

[parachains.collator]
name = "turing-col-1"
command = "./target/release/oak-collator"
ws_port = 9946
rpc_port = 8855

[[parachains]]
id = 1000
cumulus_based = true
chain = "moonbase-local"

[parachains.collator]
name = "moonbase-col-1"
command = "../moonbeam/target/release/moonbeam"
ws_port = 9949
rpc_port = 8868
