[settings]
provider = "native"
timeout = 1000

[relaychain]
default_command = "../polkadot-sdk/target/release/polkadot"
chain = "rococo-local"

    [[relaychain.nodes]]
    name = "alice"
    ws_port = 60613
    rpc_port = 8850

    [[relaychain.nodes]]
    name = "bob"
    ws_port = 60614
    rpc_port = 8851

[[parachains]]
id = 1000
cumulus_based = true
chain = "moonbase-local"

    [parachains.collator]
    name = "moonbase-local-col-1"
    command = "../moonbeam/target/release/moonbeam"
    args = ["-lxcm=trace --state-pruning archive"]
    ws_port = 9949
    rpc_port = 8868
