[settings]
provider = "native"
timeout = 1000

[relaychain]
default_command = "../polkadot/target/release/polkadot"
chain = "rococo-local"

    [[relaychain.nodes]]
    name = "alice"
    ws_port = 60613
    rpc_port = 8850

    [[relaychain.nodes]]
    name = "bob"
    ws_port = 60614
    rpc_port = 8851

[[parachains]]
id = 2114
cumulus_based = true
chain = "turing-dev"

    [parachains.collator]
    name = "turing-col-1"
    command = "./target/release/oak-collator"
    ws_port = 9946
    rpc_port = 8855

[[parachains]]
id = 2000
cumulus_based = true
chain = "shibuya-dev"

    [parachains.collator]
    name = "shibuya-col-1"
    command = "../Astar/target/release/astar-collator"
    args = ["--enable-evm-rpc"]    # EVM RPC for Metamsk: http://localhost:9948 and Shibuya Chain Id: 81
    ws_port = 9948
    rpc_port = 8867

[[hrmp_channels]]
sender = 2114
recipient = 2000
max_capacity = 8
max_message_size = 102400

[[hrmp_channels]]
sender = 2000
recipient = 2114
max_capacity = 8
max_message_size = 102400
