
//! Autogenerated weights for `pallet_xcmp_handler`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2022-07-28, STEPS: `1`, REPEAT: 12, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! EXECUTION: Some(Wasm), WASM-EXECUTION: Compiled, CHAIN: Some("dev"), DB CACHE: 1024

// Executed Command:
// ./target/release/oak-collator
// benchmark
// pallet
// --chain
// dev
// --execution
// wasm
// --wasm-execution
// compiled
// --pallet
// pallet_xcmp_handler
// --extrinsic
// *
// --repeat
// 12
// --output
// ./pallets/xcmp-handler/src/raw-weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(clippy::unnecessary_cast)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use sp_std::marker::PhantomData;

/// Weight functions needed for xcmp_handler.
pub trait WeightInfo {
	fn add_chain_currency_data() -> Weight;
	fn remove_chain_currency_data() -> Weight;
}

impl WeightInfo for () {
 	// Storage: XcmpHandler XcmChainCurrencyData (r:0 w:1)
	fn add_chain_currency_data() -> Weight {
		(12_000_000 as Weight)
			.saturating_add(RocksDbWeight::get().writes(1 as Weight))
	}
	// Storage: XcmpHandler XcmChainCurrencyData (r:1 w:1)
	fn remove_chain_currency_data() -> Weight {
		(14_000_000 as Weight)
			.saturating_add(RocksDbWeight::get().reads(1 as Weight))
			.saturating_add(RocksDbWeight::get().writes(1 as Weight))
	}
}
