// This file is part of Substrate.

// Copyright (C) 2022 Parity Technologies (UK) Ltd.
// SPDX-License-Identifier: Apache-2.0

// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//! Autogenerated weights for pallet_xcmp_handler
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2023-05-23, STEPS: `50`, REPEAT: 20, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! HOSTNAME: `actions-runner-1`, CPU: `Intel(R) Xeon(R) E-2388G CPU @ 3.20GHz`
//! EXECUTION: Some(Wasm), WASM-EXECUTION: Compiled, CHAIN: Some("turing-dev"), DB CACHE: 1024

// Executed Command:
// ./oak-collator
// benchmark
// pallet
// --chain
// turing-dev
// --execution
// wasm
// --wasm-execution
// compiled
// --pallet
// pallet_xcmp_handler
// --extrinsic
// *
// --repeat
// 20
// --steps
// 50
// --output
// ./xcmp_handler-raw-weights.rs
// --template
// ./.maintain/frame-weight-template.hbs

// Summary:
//:set_asset_config 10_886_000
//:remove_asset_config 15_615_000

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use sp_std::marker::PhantomData;

/// Weight functions needed for pallet_xcmp_handler.
pub trait WeightInfo {
	fn set_transact_info() -> Weight;
	fn remove_transact_info() -> Weight;
}

/// Weights for pallet_xcmp_handler using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	// Storage: XcmpHandler DestinationAssetConfig (r:0 w:1)
	// Proof Skipped: XcmpHandler DestinationAssetConfig (max_values: None, max_size: None, mode: Measured)
	fn set_transact_info() -> Weight {
		Weight::from_ref_time(10_886_000 as u64)
			.saturating_add(T::DbWeight::get().writes(1 as u64))
	}
	// Storage: XcmpHandler DestinationAssetConfig (r:1 w:1)
	// Proof Skipped: XcmpHandler DestinationAssetConfig (max_values: None, max_size: None, mode: Measured)
	fn remove_transact_info() -> Weight {
		Weight::from_ref_time(15_615_000 as u64)
			.saturating_add(T::DbWeight::get().reads(1 as u64))
			.saturating_add(T::DbWeight::get().writes(1 as u64))
	}
}

// For backwards compatibility and tests
impl WeightInfo for () {
	// Storage: XcmpHandler DestinationAssetConfig (r:0 w:1)
	// Proof Skipped: XcmpHandler DestinationAssetConfig (max_values: None, max_size: None, mode: Measured)
	fn set_transact_info() -> Weight {
		Weight::from_ref_time(10_886_000 as u64)
			.saturating_add(RocksDbWeight::get().writes(1 as u64))
	}
	// Storage: XcmpHandler DestinationAssetConfig (r:1 w:1)
	// Proof Skipped: XcmpHandler DestinationAssetConfig (max_values: None, max_size: None, mode: Measured)
	fn remove_transact_info() -> Weight {
		Weight::from_ref_time(15_615_000 as u64)
			.saturating_add(RocksDbWeight::get().reads(1 as u64))
			.saturating_add(RocksDbWeight::get().writes(1 as u64))
	}
}
