
//! Autogenerated weights for `pallet_automation_time`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2022-05-26, STEPS: `1`, REPEAT: 20, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! EXECUTION: Some(Wasm), WASM-EXECUTION: Compiled, CHAIN: Some("dev"), DB CACHE: 128

// Summary:
//:emit_event 20_000_000
//:reset_asset 200_000_000
//:run_native_transfer_task 230_000_000

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weight functions needed for pallet_automation_time.
pub trait WeightInfo {
	fn emit_event() -> Weight;
	fn run_native_transfer_task() -> Weight;
	fn reset_asset(v: u32, ) -> Weight;
	fn update_asset_reset() -> Weight;
	fn delete_asset_tasks() -> Weight;
	
	fn delete_asset_extrinsic() -> Weight;
	fn asset_price_update_extrinsic() -> Weight;
	fn add_asset_extrinsic() -> Weight;
	fn schedule_transfer_task_extrinsic() -> Weight;
}

impl WeightInfo for () {
	fn emit_event() -> Weight {
		Weight::from_parts(20_000_000, 5000)
	}
	fn run_native_transfer_task() -> Weight {
		Weight::from_parts(230_000_000, 5000)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	fn reset_asset(v: u32, ) -> Weight {
		Weight::from_parts(200_000_000, 5000)
			.saturating_add(RocksDbWeight::get().writes(1_u64))
			.saturating_add(Weight::from_parts(20_000_000, 0).saturating_mul(v.into()))
			.saturating_add(RocksDbWeight::get().reads((4_u64).saturating_mul(v.into())))
			.saturating_add(RocksDbWeight::get().writes((5_u64).saturating_mul(v.into())))
	}
	fn update_asset_reset() -> Weight{
		Weight::from_parts(200_000_000, 5000)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	fn delete_asset_tasks() -> Weight{
		Weight::from_parts(200_000_000, 5000)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(3_u64))
	}
	fn delete_asset_extrinsic() -> Weight{
		Weight::from_parts(220_000_000, 5000)
			.saturating_add(RocksDbWeight::get().reads(3_u64))
			.saturating_add(RocksDbWeight::get().writes(7_u64))
	}
	fn asset_price_update_extrinsic() -> Weight{
		Weight::from_parts(220_000_000, 5000)
			.saturating_add(RocksDbWeight::get().reads(5_u64))
			.saturating_add(RocksDbWeight::get().writes(3_u64))
			.saturating_add(RocksDbWeight::get().reads(21_u64))
			.saturating_add(RocksDbWeight::get().writes(21_u64))
	}
	fn add_asset_extrinsic() -> Weight{
		Weight::from_parts(220_000_000, 5000)
			.saturating_add(RocksDbWeight::get().reads(4_u64))
			.saturating_add(RocksDbWeight::get().writes(5_u64))
	}
	fn schedule_transfer_task_extrinsic() -> Weight{
		Weight::from_parts(200_000_000, 5000)
			.saturating_add(RocksDbWeight::get().reads(6_u64))
			.saturating_add(RocksDbWeight::get().writes(4_u64))
	}
}
