# https://github.com/open-web3-stack/parachain-launch
# Relaychain Configuration
# `parachain-launch  generate --config=parachain-launch/config.yml --output=parachain-launch`
relaychain:
  image: parity/polkadot:v0.9.29 # the docker image to use
  chain: rococo-local # the chain to use
  runtimeGenesisConfig: # additonal genesis override
    configuration:
      config:
        validation_upgrade_cooldown: 10
        validation_upgrade_delay: 10
  env: # environment variables for all relaychain nodes
    RUST_LOG: parachain::candidate-backing=trace
  flags: # additional CLI flags for all relaychain nodes
    - --rpc-methods=unsafe
  nodes: # nodes config
    - name: alice # the node name and session key, this imply `--alice`
      wsPort: 9944 # default ws port number is `9944 + global_node_index`
      rpcPort: 9933 # default rpc port number is `9933 + global_node_index`
      port: 30333 # default libp2p port number is `30333 + global_node_index`
      flags: # additional CLI flags for this node
        - --force-authoring
      env:
        RUST_LOG: babe=debug # environment varitables for this node
    - name: bob
    - name: charlie

# Parachain Configuration
parachains:
# Config for first parachain
- image: oaknetwork/neumann:latest
  chain: local
  id: 2000 # override parachain id
  parachain: true # this is parachain, not parathread
  flags: # CLI flags for this parachain nodes
    - --rpc-methods=unsafe
    - --force-authoring
    - --execution=wasm
  relaychainFlags: # CLI flags for the relaychain port
    - --execution=wasm
  nodes: # nodes config
  - wsPort: 9947
    rpcPort: 9936
    port: 30336
    flags: # additional CLI flags for this node
      - --alice
    relaychainFlags: # additional CLI flags for relaychain part
      - --name=relaychain-alice
  - flags:
    - --bob
