name: Benchmark

on:
  pull_request:
  # workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-binary:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.tag }}
      - name: Setup Rust
        run: rustup show
      - name: Build
        run: |
          cargo build --release --features runtime-benchmarks,turing-node
          mkdir -p artifacts/
          cp target/release/oak-collator artifacts/
      - name: Upload binary
        uses: actions/upload-artifact@v2
        with:
          name: oak-collator
          path: artifacts/
          retention-days: 1
  run-benchmarks:
    name: Run Benchmarks
    runs-on: self-hosted
    needs: build-binary
    strategy:
      matrix:
        pallet:
          - automation_time
          - vesting
          - valve
          - xcmp_handler
    steps:
      - name: Download binary
        uses: actions/download-artifact@v2
        with:
          name: oak-collator
      - name: Execute pallet benchmark
        run: |
          chmod +x oak-collator
          ./oak-collator \
            benchmark \
            pallet \
            --chain turing-dev \
            --execution wasm \
            --wasm-execution compiled \
            --pallet pallet_${{ matrix.pallet }} \
            --extrinsic '*' \
            --repeat 20 \
            --steps 50 \
            --output ./${{ matrix.pallet }}-raw-weights.rs
      - name: Delete binary artifact
        uses: geekyeggo/delete-artifact@v1
        with:
          name: oak-collator
      - name: Upload raw weights
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.pallet }}
          path: ${{ matrix.pallet }}-raw-weights.rs
  generate-pull-request:
    name: Generate pull request
    needs: run-benchmarks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Download benchmark files
        uses: actions/download-artifact@v2
      - name: Move benchmark files to correct place
        run: |
          ls \
            | grep raw-weights.rs \
            | xargs -I{} sh -c 'mv "$1" "pallets/${1%%-*}/src/weights.rs"' -- {}
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          title: Update pallet weights
          draft: true
