name: Check Set-Up, Build, Test

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches:
    - master
  pull_request:
    types: [opened, reopened, synchronize, closed]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  linting:
    name: "Check rustfmt"
    runs-on: ubuntu-latest
    if: github.event.action != 'close'
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Rust
      run: rustup show
    - name: rustfmt
      run: cargo fmt -- --check
  build:
    name: "Build release"
    runs-on: self-hosted
    if: github.event.action != 'close'
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Rust
      run: rustup show
    - name: Build
      run: |
        cargo build --release --all --features all-nodes
    - name: Test
      run: |
        cargo test --release --all --features all-nodes
  dependencies-pr-status:
    name: "Dependencies PR status"
    runs-on: ubuntu-latest
    if: (contains(github.event.pull_request.title, 'dependenc') || contains(github.event.pull_request.title, 'Dependenc')) && ( github.event.action == 'opened' || github.event.action == 'reopened' || github.event.pull_request.merged == true)
    steps:
      - name: Report PR merged to slack
        if: ${{ github.event.pull_request.merged == true }}
        uses: ravsamhq/notify-slack-action@v1
        with:
          status: ${{ job.status }}
          notification_title: 'Dependencies update PR merged'
          message_format: '${{ github.event.pull_request.title }} ${{ github.event.pull_request.html_url }}'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      - name: Report PR opened to slack
        if: ${{ github.event.action == 'opened' || github.event.action == 'reopened' }}
        uses: ravsamhq/notify-slack-action@v1
        with:
          status: ${{ job.status }}
          notification_title: 'Dependencies update PR ${{ github.event.action }}'
          message_format: '${{ github.event.pull_request.title }} ${{ github.event.pull_request.html_url }}'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
