name: Check Set-Up, Build, Test

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches:
    - master
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  linting:
    name: "Check rustfmt"
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Rust
      run: rustup show
    - name: rustfmt
      run: cargo fmt -- --check
  build:
    name: "Build release"
    runs-on: self-hosted
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Rust
      run: rustup show
    - name: Build
      run: |
        cargo build --release --all --features all-nodes
    - name: Test
      run: |
        cargo test --release --all --features all-nodes
