name: Check Set-Up, Build, Test

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  check-build:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Set-Up
        run: sudo apt install -y cmake pkg-config libssl-dev git build-essential clang libclang-dev curl

      - name: Install Rustup
        run: |
          curl https://sh.rustup.rs -sSf | sh -s -- -y
          source ~/.cargo/env

      - name: Check Build
        run: |
          SKIP_WASM_BUILD=1 cargo check --release

  test-coverage:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Set-Up
        run: sudo apt install -y cmake pkg-config libssl-dev git build-essential clang libclang-dev curl

      - name: Install Rustup
        run: |
          curl https://sh.rustup.rs -sSf | sh -s -- -y
          source ~/.cargo/env
          rustup update stable
          rustup component add llvm-tools-preview
          cargo install grcov

      - name: Test coverage
        run: |
          export CARGO_INCREMENTAL=0
          export SKIP_BUILD_WASM=true
          export BUILD_DUMMY_WASM_BINARY=true
          export LLVM_PROFILE_FILE="llvmcoveragedata-%p-%m.profraw"
          export WASM_TARGET_DIRECTORY=/tmp/wasm
          cargo build
          export RUSTFLAGS="-Zinstrument-coverage"
          rm -rf target/debug
          cargo test --all
          grcov . --binary-path ./target/debug/ -s . -t lcov --branch --ignore-not-existing --ignore "/*" -o lcov.info
          bash <(curl -s https://codecov.io/bash) -f lcov.info
          