name: Publish Neumann Docker Image

on:
  workflow_dispatch:
    inputs:
      tag:
        description: Tag for release
        required: true

jobs:
  build-binary:
    name: Build Binary
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.tag }}
      - name: Setup Rust
        run: rustup show
      - name: Build
        run: |
          cargo build --locked --release --features neumann-node --features dev-queue
          mkdir -p artifacts/
          cp target/release/oak-collator artifacts/
      - name: Upload binary
        uses: actions/upload-artifact@v2
        with:
          name: oak-collator
          path: artifacts/
  build-docker:
    name: Build Docker
    runs-on: ubuntu-latest
    needs: build-binary
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.tag }}
      - name: Download binary
        uses: actions/download-artifact@v2
        with:
          name: oak-collator
      - name: Build
        run: |
          tag=${{ github.event.inputs.tag }}
          docker_tag="${tag:1}"
          docker build -f ./docker/neumann/Dockerfile -t oaknetwork/neumann:$docker_tag .
          docker tag oaknetwork/neumann:$docker_tag oaknetwork/neumann:latest
          docker push oaknetwork/neumman:$docker_tag
          docker push oaknetwork/neumann:latest
