name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: Tag for this release
        required: true

jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps:
      - name: Say hello
        run: echo Hello, world!
