name: Release

on:
  pull_request:
  # workflow_dispatch:
  #   inputs:
  #     tag:
  #       description: Tag for release
  #       required: true

jobs:
  build-binary:
    name: Build Binary
    runs-on: self-hosted
    stes:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: v1.4.0 # ${{ github.event.inputs.tag }}
      - name: Setup Rust
        run: rustup show
      - name: Build
        run: cargo build --locked --release --features turing-node
  build-runtime:
    name: Build Runtime
    runs-on: ubuntu-latest
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: v1.4.0 # ${{ github.event.inputs.tag }}
      - name: Build
        id: srtool_build
        uses: chevdor/srtool-actions@v0.4.0
        with:
          chain: turing
  build-docker:
    name: Build Docker
    runs-on: ubuntu-latest
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: v1.4.0 # ${{ github.event.inputs.tag }}
      - name: Build
        run: |
          docker build -f ./docker/turing/Dockerfile -t oaknetwork/turing:1.4.0 . # ${{ github.event.inputs.tag }} .
