name: Release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: Tag for release
        required: true

jobs:
  build-binary:
    name: Build Binary
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.tag }}
      - name: Setup Rust
        run: rustup show
      - name: Build
        run: |
          cargo build --locked --release --features turing-node
          mkdir -p artifacts/
          cp target/release/oak-collator artifacts/
      - name: Build debian
        run: |
          cargo install cargo-deb
          cargo deb -p oak-node -- --release --features turing-node
          cp target/debian/*.deb artifacts/
      - name: Upload binary
        uses: actions/upload-artifact@v2
        with:
          name: oak-collator
          path: artifacts/
  build-runtime:
    name: Build Runtime
    runs-on: ubuntu-latest
    strategy:
      matrix:
        chain: ["turing", "oak"]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.tag }}
      - name: Build
        id: srtool_build
        uses: chevdor/srtool-actions@v0.5.0
        with:
          chain: ${{ matrix.chain }}
      - name: Summary
        run: |
          echo '${{ steps.srtool_build.outputs.json }}' | jq . > ${{ matrix.chain }}-srtool-digest.json
          cat ${{ matrix.chain }}-srtool-digest.json
          cp ${{ steps.srtool_build.outputs.wasm_compressed }} ${{ matrix.chain }}-runtime.wasm
      - name: Upload runtime
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.chain }}-runtime
          path: |
            ${{ matrix.chain }}-runtime.wasm
            ${{ matrix.chain }}-srtool-digest.json
  build-docker:
    name: Build Docker
    runs-on: ubuntu-latest
    needs: build-binary
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.tag }}
      - name: Download binary
        uses: actions/download-artifact@v2
        with:
          name: oak-collator
      - name: Build
        run: |
          tag=${{ github.event.inputs.tag }}
          docker_tag="${tag:1}"
          docker build -f ./docker/turing/Dockerfile -t oaknetwork/turing:$docker_tag .
          docker tag oaknetwork/turing:$docker_tag oaknetwork/turing:latest
          docker push oaknetwork/turing:$docker_tag
          docker push oaknetwork/turing:latest
  release:
    name: Release
    runs-on: ubuntu-latest
    needs:
      - build-binary
      - build-runtime
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.tag }}
          fetch-depth: 0
      - name: Download all artifacts
        uses: actions/download-artifact@v2
        with:
          path: artifacts
      - name: Install tree
        run: sudo apt-get install -y tree
      - name: Show the directory tree
        run: tree artifacts
